const rows = [
  ['panelLength', 'Panel name must be at most 128 characters', 'Der Panelname darf höchstens 128 Zeichen enthalten', 'Le nom du panneau doit comporter au maximum 128 caractères', 'El nombre del panel debe tener como máximo 128 caracteres'],
  ['panelStorage', 'This browser cannot save its panel name', 'Dieser Browser kann seinen Panelnamen nicht speichern', 'Ce navigateur ne peut pas enregistrer le nom de son panneau', 'Este navegador no puede guardar el nombre de su panel'],
  ['wallSession', 'Open Edit → Model as an administrator in 3D, then cancel unfinished changes before preparing exact wall meshes.', 'Öffne Bearbeiten → Modell als Administrator in 3D und verwirf unvollständige Änderungen, bevor du die genauen Wandnetze vorbereitest.', 'Ouvrez Modifier → Modèle en tant qu’administrateur en 3D, puis annulez les modifications inachevées avant de préparer les maillages exacts des murs.', 'Abre Editar → Modelo como administrador en 3D y cancela los cambios sin terminar antes de preparar las mallas exactas de las paredes.'],
  ['wallPending', 'Wall meshes are already being prepared. Wait for the model to finish loading.', 'Die Wandnetze werden bereits vorbereitet. Warte, bis das Modell vollständig geladen ist.', 'La préparation des maillages des murs est déjà en cours. Attendez la fin du chargement du modèle.', 'Las mallas de las paredes ya se están preparando. Espera a que termine de cargarse el modelo.'],
  ['wallChanged', 'The model or editing session changed during preparation. Try again with the current model.', 'Das Modell oder die Bearbeitungssitzung hat sich während der Vorbereitung geändert. Versuche es mit dem aktuellen Modell erneut.', 'Le modèle ou la session de modification a changé pendant la préparation. Réessayez avec le modèle actuel.', 'El modelo o la sesión de edición cambió durante la preparación. Inténtalo de nuevo con el modelo actual.'],
  ['wallUnavailable', 'The model could not provide separate original wall meshes.', 'Das Modell konnte keine getrennten ursprünglichen Wandnetze bereitstellen.', 'Le modèle n’a pas pu fournir les maillages originaux séparés des murs.', 'El modelo no pudo proporcionar las mallas originales separadas de las paredes.'],
  ['modelLoad', 'Could not load model {label}', 'Modell {label} konnte nicht geladen werden', 'Impossible de charger le modèle {label}', 'No se pudo cargar el modelo {label}'],
  ['presetAmbiguous', "Several presets are named '{name}'; use the view ID", "Mehrere Ansichten heißen '{name}'; verwende die Ansichts-ID", "Plusieurs vues portent le nom '{name}' ; utilisez l’identifiant de la vue", "Varias vistas se llaman '{name}'; usa el identificador de la vista"],
  ['presetMissing', "No visible preset has ID or name '{name}'", "Keine sichtbare Ansicht hat die ID oder den Namen '{name}'", "Aucune vue visible ne porte l’identifiant ou le nom '{name}'", "Ninguna vista visible tiene el identificador o nombre '{name}'"],
  ['presetWebsocket', 'The Home Assistant websocket is unavailable; the preset request cannot be confirmed', 'Die WebSocket-Verbindung zu Home Assistant ist nicht verfügbar; die Ansichtsanforderung kann nicht bestätigt werden', 'La connexion WebSocket de Home Assistant est indisponible ; la demande de vue ne peut pas être confirmée', 'La conexión WebSocket de Home Assistant no está disponible; no se puede confirmar la solicitud de vista'],
];
export default Object.fromEntries(['en', 'de', 'fr', 'es'].map((language, index) => [language,
  Object.fromEntries(rows.map(([key, ...values]) => [`runtimeNotice.${key}`, values[index]]))]));
