name: HACS validation

on:
  push:
    branches: [main]
  pull_request:

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: hacs/action@main
        with:
          category: integration
          ignore: brands
